#!/usr/bin/env python
from os import path
Import('build env module')

build.add_thirdparty(env, 'poco')
env.Append(LIBS=['tiappmodule'])
env.Append(LIBPATH=[build.get_module('tiapp').dir])
if build.is_osx():
	env.Append(FRAMEWORKS = ['Cocoa'])

env.Append(CPPDEFINES = ('TITANIUM_FILESYSTEM_API_EXPORT', 1))
env.Append(CPPPATH = ['%s/modules/ti.App' % build.titanium_source_dir])
env.Append(LIBPATH=[path.join(build.dir, 'modules', 'ti.App')])

if build.is_win32():
	env.Append(CCFLAGS=['/MD'])
	env.Append(LIBS=['shell32', 'user32', 'comdlg32', 'ole32'])
	env.Append(CPPDEFINES = ('WIN32_LEAN_AND_MEAN',1))

build.mark_build_target(env.SharedLibrary(
	path.join(module.dir, 'tifilesystemmodule'), Glob('*.cpp')))
