#!/usr/bin/env python
Import('build')
import os

# These each have their own line because we can comment
# them out easily if we need temporarily disable one.
modules = [
	'ti.App', 
	'ti.UI',
	'ti.Network',
	'ti.Growl',
	'ti.Filesystem',
	'ti.Media',
	'ti.Desktop',
	'ti.Platform',
	'ti.Process',
	'ti.Notification',
	'ti.Monkey',
	'ti.Analytics',
	'ti.Database',
	'ti.Worker'
]

for module in modules:
	module_dir = os.path.join(build.dir, 'objs', 'modules', module)
	SConscript(os.path.join(module,'SConscript'), build_dir=module_dir, duplicate=0)

