#!/usr/bin/env python

import os.path as p, os, futils
import glob, distutils.dir_util as dir_util
from app import App
from subprocess import Popen
Import('build')

t = build.env.PackageApp('#drillbit-target',
	[Dir('Resources'), Dir('modules'),
		Glob('manifest*'), 'drillbit_cmd.py', 'tiapp.xml', 'tiapp_harness.xml'],
	FULLNAME='Drillbit',
	ID='com.titaniumapp.unittest.driver',
	GUID='D83B08F4-B43B-4909-9FEE-336CDB44750B',
	INSTALLED=True)

Depends(t, build.build_targets + build.staging_targets)
Alias('drillbit', t)
