#!/usr/bin/env python
from os import path
Import('build env module')

env.Append(CPPDEFINES = ('TITANIUM_CODEC_API_EXPORT', 1))

build.add_thirdparty(env, 'poco')

if build.is_win32():
	env.Append(CCFLAGS=['/MD', '/DUNICODE', '/D_UNICODE'])

build.mark_build_target(env.SharedLibrary(
	path.join(module.dir, 'ticodecmodule'), Glob('*.cpp')))
