#!/usr/bin/env python
import os
Import('build')

env = build.env.Clone();
env.Append(CPPDEFINES = ('TITANIUM_CODEC_API_EXPORT', 1))
env.Append(CPPPATH = ['#kroll'])
build.add_thirdparty(env, 'poco')

m = build.add_module('ti.codec')
t = env.SharedLibrary(target = m.build_dir + '/ticodecmodule', source = Glob('*.cpp'))
build.mark_build_target(t)

t = build.utils.CopyTree(Glob('*.js'), m.build_dir)
build.mark_build_target(t)

