#!/usr/bin/env python

import os.path as p, os 
import glob, distutils.dir_util as dir_util
Import('build')

t = build.env.PackageApp('#testapp-target',
	[Dir('Resources'), 'tiapp.xml'],
	FULLNAME='Testapp',
	ID='com.titaniumapp.testapp',
	GUID='D36DD8BA-D092-4F20-9073-EB613BFB8F46',
	PUBLISHER='Appcelerator, Inc.',
	URL='http://www.titaniumapp.com',
	VERSION=build.version,
	INSTALLED=True)
Depends(t, build.build_targets + build.staging_targets)
Alias('testapp', t)

