#!/usr/bin/env python

import os.path as p, os
import glob, distutils.dir_util as dir_util
from app import App
from subprocess import Popen
Import('build')

common_dir = p.join(build.titanium_source_dir,'installation','common')

t = build.env.PackageApp('#alloy-target',
	[Dir('Resources'), Dir('modules'), Glob('manifest*'), 'tiapp.xml'],
	FULLNAME='Alloy',
	ID='com.titaniumapp.alloy',
	GUID='be69fe4c-966b-483c-b57c-7ba4a34fbf10',
	RESOURCES=[],
	INSTALLED=True)

Depends(t, build.build_targets + build.staging_targets)
Alias('alloy', t)
