#!/usr/bin/env python
import os, os.path as path

Import('build')

env = build.env.Clone();
env.Append(CPPPATH = ['#kroll'])
env.Append(CPPDEFINES=['USE_NO_EXPORT=1', 'UNICODE=1', '_UNICODE=1'])
build.add_thirdparty(env, 'poco')

env.Append(CPPPATH=[build.kroll_utils_dir])
env.Append(LIBS=['msi', 'user32', 'shell32', 'iphlpapi', 'advapi32', 'wininet', 'urlmon'])
ccf = env['CCFLAGS'][:]
if '/MD' in ccf: ccf.remove('/MD')
ccf.append('/MT')
env['CCFLAGS'] = ccf

sources = Glob('*.cpp')
sources.extend(build.get_kroll_utils(path.join(build.dir, 'objs', 'netinstaller')))

t = env.SharedLibrary(target = path.join(build.runtime_build_dir, 'installer', 'titanium_installer'), source = sources)
build.mark_build_target(t)