#!/usr/bin/env python
import os, inspect, os.path as path, shutil
import distutils.dir_util as dirutil

Import('build')

env = build.env.Clone();
env.Append(CPPDEFINES = ('TITANIUM_GROWL_API_EXPORT', 1))
env.Append(CPPPATH = ['#kroll'])

build.add_thirdparty(env, 'poco')
sources = Glob('*.cpp')

if build.is_osx():
	env.Append(FRAMEWORKPATH=[build.tp('growl')])
	env.Append(FRAMEWORKS=['Cocoa', 'Growl'])
	sources += Glob(build.os + '/*.mm')
	sources += Glob('%s/*.cpp' % build.os)

elif build.is_win32():
	env.Append(CCFLAGS=['/MD', '/DUNICODE', '/D_UNICODE'])
	env.Append(LIBS = ['user32', 'shell32', 'advapi32', 'khost'])
	sources += Glob('%s/*.cpp' % build.os)

elif build.is_linux():
	sources += Glob('libnotify/*.cpp')
	env.ParseConfig('pkg-config --cflags --libs libnotify')

m = build.add_module('ti.Growl', env=env)
t = env.SharedLibrary(target = m.build_dir + '/tigrowlmodule', source=sources)
build.mark_build_target(t)
