#!/usr/bin/env python
from os import path
Import('build env module')

env.Append(CPPDEFINES = ('TITANIUM_PLATFORM_API_EXPORT', 1))
env.Append(CPPPATH = ['#kroll'])
build.add_thirdparty(env, 'poco')

if build.is_win32():
	env.Append(CCFLAGS=['/MD', '/DUNICODE', '/D_UNICODE'])
	env.Append(LIBS=['Advapi32', 'Iphlpapi', 'user32', 'shell32', 'gdi32'])
	env.Append(CPPDEFINES = ('WIN32_LEAN_AND_MEAN',1))

elif build.is_osx():
	env.Append(FRAMEWORKS = ['AppKit', 'Cocoa'])

sources = [File('platform_module.cpp'), File('platform_binding.cpp')]
if build.is_osx():
	sources.append(File('platform_binding_%s.mm' % build.os))
else:
	sources.append(File('platform_binding_%s.cpp' % build.os))

build.mark_build_target(env.SharedLibrary(
	path.join(module.dir, 'tiplatformmodule'), sources))
