#!/usr/bin/env python
import os, os.path as path
Import('build')

env = build.env.Clone();
env.Append(CPPDEFINES=['USE_NO_EXPORT=1', 'UNICODE=1', '_UNICODE=1'])
build.add_thirdparty(env, 'poco')
env.Append(LIBS=['msi', 'user32', 'shell32', 'iphlpapi', 'advapi32', 'wininet', 'urlmon'])

# Compile against the MSVSCRT statically.
ccf = env['CCFLAGS'][:]
if '/MD' in ccf:
	ccf.remove('/MD')
ccf.append('/MT')
env['CCFLAGS'] = ccf

env.Append(CPPPATH=[build.kroll_utils_dir])

dest = path.join(build.dir, 'sdk', 'installer', 'titanium_installer')
installer_objects = Glob("*.cpp")
installer_objects += build.get_kroll_utils(path.join(build.dir, 'objs', 'installer'))

build.mark_build_target(env.SharedLibrary(dest, installer_objects))
