#!/usr/bin/env python
import effess
import SCons.Variables
import SCons.Environment
import os.path as path
import sys
from SCons.Script import *
from app import App
from subprocess import Popen

Import('build')
Import('run')
Import('run_with')

def package_app_builder(target, source, env):
	# Wait until the initial build is finished to do this import.
	import sdk.env

	pkg_env = sdk.env.PackagingEnvironment(build.version, build.os, 'titanium')
	app = pkg_env.App(pkg_env, env['PATH'])
	app.stage(path.join(build.dir, app.name), bundle=True)

build.env['BUILDERS']['PackageApp'] = build.env.Builder(
	action=package_app_builder,
	target_factory=SCons.Node.FS.default_fs.Entry,
	multi=0)

def make_app_target(name, path):
	t = build.env.PackageApp('#titanium-app-' + name, [], PATH=path)
	Depends(t, build.build_targets + build.staging_targets)
	Alias(name, t)

make_app_target('developer', path.normpath("%s/../../titanium_developer" % build.cwd()))
make_app_target('testapp', path.join(build.cwd(), 'testapp'))
make_app_target('drillbit', path.join(build.cwd(), 'drillbit'))
make_app_target('alloy', path.join(build.cwd(), 'alloy'))

