#!/usr/bin/env python
import os
Import('build')

env = build.env.Clone();
env.Append(CPPDEFINES = ('TITANIUM_WORKER_API_EXPORT', 1))
env.Append(CPPPATH = ['#kroll','%s/modules/javascript' % build.kroll_source_dir])
env.Append(LIBPATH=[build.get_module('javascript').build_dir])
env.Append(LIBS=['javascriptmodule'])
build.add_thirdparty(env, 'poco')

m = build.add_module('ti.Worker', env=env)
t = env.SharedLibrary(target = m.build_dir + '/tiworkermodule', source = Glob('*.cpp'))
build.mark_build_target(t)

t = build.utils.CopyTree(Glob('*.js'), m.build_dir)
build.mark_build_target(t)

