#!/usr/bin/env python
import os
Import('build')

env = build.env.Clone();
env.Append(CPPDEFINES = ('TITANIUM_DESKTOP_API_EXPORT', 1))
env.Append(CPPPATH = ['#kroll'])

build.add_thirdparty(env, 'poco')
sources = Glob('*.cpp')

if build.is_osx():
	env.Append(FRAMEWORKS = ['Cocoa'])
	sources += Glob('osx/*.mm')
elif build.is_win32():
	env.Append(LIBS=['shell32', 'user32', 'comdlg32', 'ole32', 'gdi32'])
	env.Append(CPPDEFINES = ('WIN32_LEAN_AND_MEAN', 1))
	sources += Glob('win32/*.cpp')
elif build.is_linux():
	sources += Glob('linux/*.cpp')

m = build.add_module('ti.Desktop', env=env)
t = env.SharedLibrary(target = m.build_dir + '/tidesktopmodule', source=sources)
build.mark_build_target(t)
