#!/usr/bin/env python
import os.path as p
Import('build')

script = p.join(build.os, 'SConscript')
build_dir = p.join(build.dir, 'objs', 'installer')
SConscript(script, variant_dir=build_dir, duplicate=0)
